### ISSUE TITLE
exit previous iteration whenever esc is clicked

### ISSUE THREAD

**Issue by schezfaz** [schezfaz/mice#3]
When we click esc from the keyboard currently, the run_script flag changes to false preventing the while loop from running the next iteration. However, the while loop is time controlled and waits for the previous iteration to complete [by waiting for the number of seconds: time.sleep(time_interval)] before it can terminate the entire script

**Comment by ankitshaw** [comment]
for i in range(100) :
            if run_script:
                time.sleep(time_interval/100) 
            else:
                print("breeakkkk...")    
                break

**Comment by ankitshaw** [comment]
Use this!
```
for i in range(time_interval) :
       if run_script:
           time.sleep(1) 
       else:
           print("breeakkkk...")    
           break
```

**Comment by schezfaz** [comment]
Thankyou! @ankitshaw 

Submit a PR next time 😋
